aws_region         = "us-west-2"
vpc_cidr           = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
public_key_path    = "~/.ssh/id_rsa.pub"
vpc_name           = "turjo-main-vpc"
subnet_name        = "turjo-public-subnet"
igw_name           = "turjo-igw"
route_table_name   = "turjo-public-rt"